### ISSUE TITLE
Add osx CI if possible

### ISSUE THREAD

**Issue by kamalmarhubi** [luser/read-process-memory#2]
Not sure if the weird task stuff that this library does will be allowed in the Travis environment, but ideally we'd have some good expectation of non-brokenness.

**Comment by kamalmarhubi** [comment]
This is the silliest issue I've opened all day. Sorry.

**Comment by kamalmarhubi** [comment]
Oh I knew I meant something. This was for OS X specifically.

**Comment by kamalmarhubi** [comment]
See TODO at https://github.com/luser/read-process-memory/blob/master/src/lib.rs#L282-L283

**Comment by fitzgen** [comment]
Might also be possible if running the tests with `sudo` (and there isn't a `sudo: false` in `.travis.yml`).

**Comment by luser** [comment]
It should work fine with sudo, yeah. Alternately, we can make it work on nightly Rust using [`CommandExt::before_exec`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.before_exec) to implement the technique here:
http://www.foldr.org/~michaelw/log/computers/macosx/task-info-fun-with-mach

I've intended to sit down and write a crate that implements that, but I haven't gotten around to it.

**Comment by kamalmarhubi** [comment]
I actually thought `before_exec` was already stabilized. TIL.

**Comment by luser** [comment]
`CommandExt::before_exec` hit stable in 1.15, so when I find time I will write that crate so I can write the tests. :)

**Comment by luser** [comment]
I finally wrote that crate! https://github.com/luser/rust-spawn-task-port

I need to fixup a few things before I can publish it on crates.io, and then we should be able to use it to get the tests running on OS X.

**Comment by luser** [comment]
Fixed! I published spawn-task-port as well: https://crates.io/crates/spawn-task-port
