### ISSUE TITLE
Shorten name

### ISSUE THREAD

**Issue by LogoiLab** [luser/read-process-memory#4]
I believe the name of this repo could be shortened to read-proc or dump-proc or something similar. It helps keep typing down and works better with crates.io

**Comment by frewsxcv** [comment]
I personally like read-process-memory a lot more than read-proc or dump-proc.

**Comment by Boscop** [comment]
Will it only be for reading or also for writing process memory?

**Comment by luser** [comment]
It currently only has support for reading process memory, but the platform APIs for writing process memory are all very similar, so it wouldn't be hard to add support for that if someone needed it. If someone did add those APIs I would probably want to rename the crate. :) Until that point, I kind of prefer the current verbose-but-descriptive name. If it's annoying to type in Rust code you can always alias it like `extern crate read_process_memory as readproc;`.
